### ISSUE TITLE
[STORY] As a landlord, I want to list my apartment so potential renters can see the listing

### ISSUE THREAD

**Issue by NathanCarriere** [jcsnorlax97/rentr#23]
### Associated Issues & PRs (Sprint 2)
- Issues (Dev Tasks): #62, #63, #64, #96 
- PRs: #74, #77, #82, _ (for 96)

**As a landlord, I want to be able to list my apartment so that potential renters can see the listing**

### Acceptance criteria: 
- [x] : Landlords should be able to create an apartment listing. 
- [x] : Both landlords and tenants should be able to see the listing.
- [x] : Pagination works when there is more than 1 page of listing

Estimated time: 3 days

### Dev tasks:
1. - [x] : Add a button on the home page that allows the user to add a listing.
1. - [x] : Showing all the available listings on the homepage.
2. - [x] : Pagination that allows users to go to different pages

**Comment by Mik3Qiao** [comment]
Task finished
