### ISSUE TITLE
[STORY] As a landlord, I want to add a listing

### ISSUE THREAD

**Issue by NathanCarriere** [jcsnorlax97/rentr#26]
### Associated Issues & PRs (Sprint 2)
- Issues (Dev Tasks): #65, #66, #67, #79, #96 
- PRs: #83, #85, #84, #73, #80, _ (for 96)

This will implement the "create a listing" form/dialog UI and back end. So it will entail creating a "Add listing" button for users, a form for them to input data, and a back end to store this data. 

The actual retrieval/viewing of listings will be done by #23, so don't do any of that work.

Acceptance criteria: 
  - [x] Users can click on a button to add a listing, and then a listing creation dialog appears
  - [x] Listing creation dialog/form includes fields for title, price, number of bedrooms, number of bathrooms, and description.
  - [x] Users can click a submit button on the listing creation dialog to submit their entry

Estimate: 5 days

**Comment by Mik3Qiao** [comment]
User is now able to create a listing after they logged in. Task finished

**Comment by AzizulHakim96** [comment]
![](https://github.com/jcsnorlax97/rentr/blob/develop/designAndArchitecture/AddApartmentListings.png)
