### ISSUE TITLE
[STORY] As a landlord, I want to add photos to my listing so people know what it looks like

### ISSUE THREAD

**Issue by NathanCarriere** [jcsnorlax97/rentr#27]
### Associated Issues & PRs (Sprint 2)
- Issues (Dev Tasks): #81 
- PRs: #58, #93 
 
As a landlord, I want to be able to add photos to my listing so people can see what it looks like

Acceptance test: 
- [x] Landlords can upload pictures and add it to the listing.
- [x] Listing should show pictures

Time Estimate: 5 Days

Developer tasks:
- [x] Add button on the listing details page: "upload"
- [x] Add the function for the button to upload picture in the frontend
- [x] Add the REST api "get" and "post" so pictures could be stored in the db, and picture will show after it's posted.
- [x] Test if it works for multiple listing.

**Comment by Mik3Qiao** [comment]
Finished

**Comment by AzizulHakim96** [comment]
Sequence Diagram:
https://github.com/jcsnorlax97/rentr/blob/develop/designAndArchitecture/AddapartmentPhotos.png
