### ISSUE TITLE
As a user (landlord or tenant), I want to be able to create my account.

### ISSUE THREAD

**Issue by NathanCarriere** [jcsnorlax97/rentr#35]
### Associated Issues & PRs (Sprint 2)
- Issues (Dev Tasks): #03, #51, #53, #54, #56, #57 
- PRs: #59, #70, #58

As a user (landlord or tenant), I want to be able to create my account.

Acceptance test: 
- [ ] Landlords can be able to post a listing.
- [ ] Tenants can be able to see landlords’ listings.

Estimate: 4 Days

**Comment by jcsnorlax97** [comment]
All developer tasks have been completed. All PRs have been approved and merged. Close this User Story.

**Comment by AzizulHakim96** [comment]
[https://github.com/jcsnorlax97/rentr/blob/develop/designAndArchitecture/SignUp.png](url)
