### ISSUE TITLE
[STORY] As a user (landlord or tenant), I want to be able to log in/out from my account.

### ISSUE THREAD

**Issue by NathanCarriere** [jcsnorlax97/rentr#36]
### Associated Issues & PRs (Sprint 2)
- Issues (Dev Tasks): #52, #55, #71, #96 
- PRs: #75, _ (for 55), #72, #92, _ (for 96)

As a user (landlord or tenant), I want to be able to log in/out from my account.

Acceptance test:
- [x] Users can type their login information to log in their account.
- [x] Users can log out.

Estimate: 3 Days

**Comment by Mik3Qiao** [comment]
frontend and backend implementation completed

**Comment by AzizulHakim96** [comment]
Sequence Diagram:
https://github.com/jcsnorlax97/rentr/blob/develop/designAndArchitecture/LogIn.png
