### ISSUE TITLE
Front end: Implement apartment listings

### ISSUE THREAD

**Issue by NathanCarriere** [jcsnorlax97/rentr#49]
The goal of this is to implement the "listing creation" form.

It will give options for users to specify details about their listing:

- Title 
- Description
- Number of bedrooms
- City
- Photos

This should take the user inputted data and send it to the backend.

Relates to #23

**Comment by NathanCarriere** [comment]
If you take this on, feel free to add sub-tasks to this (not sure if Github allows sub-tasks to be set up)

**Comment by jcsnorlax97** [comment]
@NathanCarriere This issue is duplicated to Issue #65 and Issue #66. Close this issue.
