### ISSUE TITLE
Back end: Implement apartment listings

### ISSUE THREAD

**Issue by NathanCarriere** [jcsnorlax97/rentr#50]
Double check that this doesn't overlap with a dev task for #26 

- [ ] Create a back end POST route for the information in #49: 

- Title
- Description
- Number of bedrooms
- City
- Photos

- [ ] Perform a DB update to store this information.

This should not involve creating a GET route. That should be a #26 dev task.

**Comment by jcsnorlax97** [comment]
@NathanCarriere, I think this dev task issue is the same as #73. Can we remove all the labels, and unlink this from the project & milestones?

**Comment by NathanCarriere** [comment]
@jcsnorlax97 Yes, I think I meant to remove this but forgot to.
