### ISSUE TITLE
Homepage Layout - Header Component

### ISSUE THREAD

**Issue by jcsnorlax97** [jcsnorlax97/rentr#53]
### Associated User Story: 
#35 

### Task Description:
- This ticket aims to implement a basic Rentr homepage layout for account management.
- The homepage layout consists of a Header component.
- The Header component should consists of two things:
   1. a Rentr Icon / Rentr Title on the top left, telling user the app they're using.
   2. a Login button or hyperlink text.
      - This ticket does not involve any behaviour implementation; the behavioural implementation would belong to another ticket.

### Dependencies:
N/A

### Acceptance Criteria:
1. A Rentr Icon / Rentr Title is on the top left side of the page.
2. A Login button / hyperlink text is on the top right side of the page.
3. The Login button / hyperlink should be inside a component called Header. 2
4. The Header component can be rendered via App.js.

**Comment by Mik3Qiao** [comment]
Implemented header component, issue complete
