### ISSUE TITLE
Login Prompt Popping Event Handler

### ISSUE THREAD

**Issue by jcsnorlax97** [jcsnorlax97/rentr#54]
### Associated User Story: 
#35, #36 

### Task Description:
- This ticket aims to implement the behaviour of popping login prompt when the login button is clicked.
- The login prompt should look like: 
![Screen Shot 2021-02-08 at 7 51 34 PM](https://user-images.githubusercontent.com/36612705/107304695-36d3bb00-6a47-11eb-808e-daec9cdbeac3.png)
- When an entry (either the one for email or password) is empty, it should display "sample@email.com" as a default text, and "password" as a default text.
- The entered password should be shown as black bullet points instead of actual passwords.
- The behavioural implementation of Login button and Registration button do not need to be implemented yet. (It would be in another ticket.)

### Dependencies:
#53 

### Acceptance Criteria:
1. When login button is clicked, it should render a login prompt with (i) an entry for email address, (ii) an entry for password, (iii) a login button, and (iv) a registration button.
2. The helper text for the "email" entry should be "sample@email.com".
3. The helper text for the "password" entry should be "password".
4. The entered password should be displayed as black bullet points instead of the actual password.

**Comment by Mik3Qiao** [comment]
Layout, together with mechanism for login function is implemented. Acceptance criteria met
