### ISSUE TITLE
[TASK] Implement a GET route for retrieving all existing listings from DB

### ISSUE THREAD

**Issue by jcsnorlax97** [jcsnorlax97/rentr#62]
### Associated User Story: 
#23 or/and #26 

### Task Description:
- This ticket aims to implement an API endpoint for front-end to retrieve all existing listings from DB.
- Route: `/api/v1/listing`
- Areas that involve updates:
   - `/api` folder (**required**)
   - `/controllers` folder (**required**)
   - `/service` folder (optional - TBD - may have another task ticket to refactor codes from this)
   - `/dao` folder (optional - TBD - may have another task ticket to refactor codes from this)
   - `/dto` folder (optional - TBD - may have another task ticket to refactor codes from this)

### Dependencies:
N/A

### Acceptance Criteria (may be updated in the future):
- `/api/v1/listing` returns a list of JSON objects, and each object should consist of fields as follows:
   1. Id,
   2. Title, 
   3. Price, 
   4. Number of bedrooms, 
   5. Number of bathrooms, and 
   6. Description.

**Comment by NathanCarriere** [comment]
The GET would now be related to #23, since #26 now only relates to the "Create a listing" form/dialog.
