### ISSUE TITLE
#26 Dev Task: Add "Create a listing" button

### ISSUE THREAD

**Issue by NathanCarriere** [jcsnorlax97/rentr#65]
User story: #26

Somewhere on the site, add a "Create a listing" button which landlords can click, which causes a "Listing creation" form/dialog to open. 

Testing criteria:
- [x] Button that says "create a listing" should appear somewhere (for now, doesn't matter much)
- [ ] (Restrict access to landlords?)
- [x] Clicking the button should result in a dialog appearing. 

Planned completion date: By Wednesday, February 17 (My estimate: 1 day of work)

Time spent so far: 2 hours

**Comment by jcsnorlax97** [comment]
PRs are approved & merged. Close this issue.
