### ISSUE TITLE
#26 Dev Task: Add form to "Create a listing" dialog. 

### ISSUE THREAD

**Issue by NathanCarriere** [jcsnorlax97/rentr#66]
User story: #26

In the dialog that appears after clicking the "Create a listing" button (see: #65), add a form inside the dialog where the user can input listing details.. This form should have a submit button that sends the form data to the back end. 

Testing criteria:
- [x] Has title field
- [x] Title field has a character limit of 100 characters and a message to user if they hit the character limit. 
- [x] Has description field
- [x] Description field has a character limit of 5000 and a message to user if they hit the character limit. 
- [x] Has number of bedrooms field.
- [x] Bedroom field should be a dropdown. Options: 1-10 bedroom, with final option being ">10"
- [x] Has number of bathrooms field
- [x] Bathrooms field should be a dropdown. Options: 1-5 bathroom, with final option being ">5"
- [x] Has submit button which passes form information to server. 

Planned completion date: By Friday, February 19 (My estimate: 2 days of work)

**Comment by jcsnorlax97** [comment]
PR is approved & merged. Close this issue.
