### ISSUE TITLE
Add Middleware Validation using JWT for routes

### ISSUE THREAD

**Issue by RonnieDsouza** [jcsnorlax97/rentr#79]
Currently, the Login POST route creates a JWT Token for authorising the login. 
This should be used to validate if a user is logged in before allowing to add listings, etc.

**Comment by jcsnorlax97** [comment]
@RonnieDsouza I've seen the PR is merged already. Can I close this ticket?

**Comment by RonnieDsouza** [comment]
Yeah! It's done!

**Comment by jcsnorlax97** [comment]
Sounds good! This issue is closed now.
